export const CLUB_CONFIG = {
  name: "Gstaad Cricket Club",
  shortName: "GCC",
  tagline: "Cricket comes to Gstaad.",
  subtagline: "Cricket for Our Community",
  description: "A free day of cricket for children, adults, families and complete beginners. Come play, learn and help us grow the game in our region.",
  crest: "/gstaad-cricket-club-crest.png",
  affiliation: {
    name: "Cricket Switzerland",
    logo: "/cricket-switzerland-logo.png",
  },
  festival: {
    title: "Gstaad Cricket Festival 2026",
    slug: "gstaad-cricket-festival-2026",
    dateDisplay: "26 September 2026",
    dateFormatted: "2026-09-26",
    timeDisplay: "11:00",
    venueName: "Ebnit School, Gstaad",
    venueAddress: "Ebnitstrasse 28, 3780 Gstaad, Switzerland",
    entryFee: "Free for everyone",
    kicker: "26 · 09 · 2026",
    headline: "One day. One pitch. A new tradition.",
    audience: [
      { id: "01", label: "Children" },
      { id: "02", label: "Adults" },
      { id: "03", label: "Families" },
      { id: "04", label: "Beginners" },
    ],
  },
  membershipTiers: [
    {
      id: "adult",
      title: "ADULT",
      price: 100,
      currency: "CHF",
      period: "per year",
      featured: false,
      tierName: "Full Playing" as const,
      description: "For active adult players participating in fixtures, training, and club sessions.",
    },
    {
      id: "family",
      title: "FAMILY",
      price: 200,
      currency: "CHF",
      period: "per year",
      featured: true,
      tierName: "Social Member" as const,
      description: "Full family household membership with access to community cricket days and social events.",
    },
    {
      id: "junior",
      title: "JUNIOR",
      price: 50,
      currency: "CHF",
      period: "per year",
      featured: false,
      tierName: "Junior" as const,
      description: "For youth under 18 wishing to learn foundational cricket skills with qualified coaching.",
    },
  ],
  memberBenefits: [
    "The Annual General Meeting",
    "The annual gala dinner",
    "Club festival events",
    "Priority access to coaching clinics and ground fixtures",
  ],
  foundingSponsors: [
    { name: "GoSwiss", logo: "/sponsor-goswiss.svg", theme: "light" },
    { name: "Cherry’s Bistro Bar and Take Away", logo: "/sponsor-cherrys.jpg", theme: "dark" },
    { name: "Mango Restaurant", logo: "/sponsor-mango.jpg", theme: "light" },
    { name: "The Boat Bar and Restaurant", logo: "/sponsor-the-boat.jpg", theme: "light" },
    { name: "Popcorn Digital", logo: "/sponsor-popcorn-digital.png", theme: "dark" },
    { name: "Gstaad Ice Cream Switzerland", logo: "/sponsor-gstaad-ice-cream.png", theme: "light" },
    { name: "Express Booking", logo: "/sponsor-express-booking.jpg", theme: "light" },
    { name: "Zwiss — Your Local Swiss Partner", logo: "/sponsor-zwiss.jpg", theme: "light" },
  ],
  communityDonors: [
    "Sathya Narayanan",
    "Linda Narayanan",
    "Ryan Narayanan",
    "Lynes Narayanan",
    "Sonali Narayanan",
    "Ueli Schwander",
    "Verene Schwander",
  ],
  committee: [
    {
      name: "Sathya Narayanan",
      initials: "SN",
      role: "President",
      icon: "shield",
      bio: "Founder of Gstaad Cricket Club. Over two decades representing Switzerland in international cricket, former captain of Cossonay Cricket Club and Bern Cricket Club, and organizer of Swiss T20.",
    },
    {
      name: "Linda Narayanan",
      initials: "LN",
      role: "Treasurer",
      icon: "wallet-cards",
      bio: "Club Treasurer overseeing financial management, donor contributions, equipment budgeting, and fiscal transparency.",
    },
    {
      name: "Thineskumar Thilakanathan",
      initials: "TT",
      role: "Head of Marketing",
      icon: "megaphone",
      bio: "Head of Marketing driving digital presence, community outreach, regional partnerships, and event promotion.",
    },
    {
      name: "Usman Ali Sheikh",
      initials: "US",
      role: "Youth Development Officer",
      icon: "users-round",
      bio: "Youth Development Officer directing grassroots coaching programs, school clinics, and junior talent pathways.",
    },
  ],
  contact: {
    email: "info@gstaadcricketclub.ch",
    location: "Gstaad, Bernese Oberland, Switzerland",
  },
} as const;
